Add notification on github ci workflow

diff --git a/.github/workflows/ios_build_with_secret.yml b/.github/workflows/ios_build_with_secret.yml
--- a/.github/workflows/ios_build_with_secret.yml
+++ b/.github/workflows/ios_build_with_secret.yml
@@ -34,6 +34,9 @@ on:
       match_file:
         description: 'Matchfile value'
         required: true
+      deploy_id:
+        description: 'Deploy id'
+        required: true
 
 jobs:
   build:
@@ -71,22 +74,62 @@ jobs:
         echo "${{ github.event.inputs.match_file}}" > fastlane/Matchfile
         cat fastlane/Matchfile
 
-    - name: test
-      run: |
-        echo "hello" > test
-        cat test
-        echo "hello world"
-        cat 1.13.0
     - name: Install dependencies
       run: |
         gem install bundler
         pod install
         bundle update --full-index
+
     - name: Execute Fastlane
-    #   env:
-    #     MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
-    #     FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
-    #     FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
-    #     FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
+      #   env:
+      #     MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
+      #     FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
+      #     FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
+      #     FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
+      uses: BuildupTeam/github_actions/run-and-capture-error@main
+      with:
+        command: fastlane deploy
+        step-name: Run Fastlane Build Lens
+        error-log-path: ${{ github.workspace }}/errors.txt
+
+    - name: Send Failure Notification
+      if: failure()
       run: |
-        fastlane deploy
+        echo "CI/CD pipeline failed. Sending API request..."
+        ERROR_MESSAGE=$(<errors.txt)
+        PAYLOAD=$(jq -n \
+        --arg auth "${{ github.event.inputs.client_app }}" \
+        --arg auth "${{ github.event.inputs.deploy_id }}" \
+        --arg run_number "${GITHUB_RUN_NUMBER}" \
+        --arg deploy_id "${GITHUB_RUN_NUMBER}" \
+        --arg msg "$ERROR_MESSAGE" \
+        '{authorization: $auth, workflow_run_number: $run_number, error_message: $msg, deploy_id: $deploy_id}')
+        curl -X POST -H "Content-Type: application/json" \
+          -d "$PAYLOAD" \
+          "https://ecommerce.buildupp.co/ci-failure"
+
+    - name: Send Success Notification
+      if: success()
+      run: |
+        echo "CI/CD pipeline failed. Sending API request..."
+        ERROR_MESSAGE=$(<errors.txt)
+        ERROR_MESSAGE_JSON=$(echo "$ERROR_MESSAGE" | jq -aRs .)
+        max_attempts=3
+        attempt=1
+        sleep_seconds=5
+        while [ $attempt -le $max_attempts ]; do
+          echo "Attempt $attempt of $max_attempts"
+          curl -X POST -H "Content-Type: multipart/form-data" \
+               -F "authorization=${{ github.event.inputs.client_app }}" \
+               -F "authorization=${{ github.event.inputs.deploy_id }}" \
+               -F "workflow_run_number=${GITHUB_RUN_NUMBER}" \
+               -F "error_message=$ERROR_MESSAGE_JSON" \
+               "https://ecommerce.buildupp.co/ec/api/ci-success" && break
+          echo "curl command failed, retrying in $sleep_seconds seconds..."
+          sleep $sleep_seconds
+          attempt=$(( attempt + 1 ))
+        done
+        if [ $attempt -gt $max_attempts ]; then
+          echo "curl command failed after $max_attempts attempts"
+          exit 1
+        fi
